make maple-mini
make generic-pc13
make generic-pd2
make generic-pd1
make generic-pa1
make generic-pb9
make generic-pe2
make generic-pa9
make generic-pe5
make generic-pb7
make generic-pb0
make generic-pb12
make mini-stm32v3